feat: implement a file provider for Azure auth
bank-vaults/bank-vaults pull request #2086
Opened 2023-08-01 15:19 UTC by akijakya

Fixes #2056

Tested with Azure

2023-08-09 13:46 UTC, ramizpolic requested changes

2023-08-09 13:46 UTC, ramizpolic commented on pkg/kv/azurekv/keyvault.go
>  		}
This looks cleaner
```go
	// Creating the default credential chain or auth file
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Debugf("falling back to creating auth file due to err=%v", err)
		if cred, err = NewFileBasedCredential(); err != nil {
			log.Fatalf("failed to create cred chain: %v", err)
		}
	}

	// Get credential
	_, err = cred.GetToken(context.Background(), policy.TokenRequestOptions{})
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}

```

2023-08-09 13:46 UTC, ramizpolic commented on pkg/kv/azurekv/keyvault.go
> +	fileLocation := os.Getenv("AZURE_AUTH_LOCATION")
Can we have this env variable defined as constant?

2023-08-09 13:46 UTC, ramizpolic commented on pkg/kv/azurekv/keyvault.go
> +	}
This can be a package-defined type named e.g. `AuthConfig`

2023-08-09 13:46 UTC, ramizpolic commented on pkg/kv/azurekv/keyvault.go
> +	contents, err := ioutil.ReadFile(fileLocation)
use `os.ReadFile` instead of deprecated ioutil package

2023-08-10 12:14 UTC, akijakya commented on pkg/kv/azurekv/keyvault.go
>  		}
The problem was that `NewDefaultAzureCredential` only creates the chain, normally it wouldn't error, but the `GetToken` method can still fail. Looking at the problem again I came up with a better solution though!

2023-08-10 12:16 UTC, akijakya commented on pkg/kv/azurekv/keyvault.go
> +	contents, err := ioutil.ReadFile(fileLocation)
These mostly came from the old Azure code I copied blindly BTW, nice catch!

2023-08-10 12:29 UTC, ramizpolic approved these changes

2023-08-10 12:29 UTC, ramizpolic commented on pkg/kv/azurekv/keyvault.go
> +	fileBasedCred azcore.TokenCredential
An idea: If you use `collection map[string]azcore.TokenCredential{"file": file, "default": default}` instead of specific fields, then you can have reusable logic in GetToken (you can loop over this map). This would also rename the `DefaultWithFileBasedCredential` to `MultiTokenCredential`.

Apart from that, looks good.

2023-08-10 14:12 UTC, ramizpolic approved these changes

2023-08-11 09:11 UTC, merged