chore: remove viper from vault file reloaders
bank-vaults/bank-vaults pull request #2105
Opened 2023-08-08 15:30 UTC by ramizpolic

## Overview

Fixes #2032 

## Notes for reviewer

2023-08-10 08:04 UTC, sagikazarmark requested changes
@ramizpolic I'm not quite sure I understand the JSON file loading part. Can you explain? Did we support that previously?

2023-08-10 08:12 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
>  	"io/ioutil"
Same question on my end, @sagikazarmark. It appeared to me that since we used Viper, we supported YAML/TOML/JSON. Do we only support YAML config files?

2023-08-10 09:56 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
>  	"io/ioutil"
Note, I have reverted to YAML-only vault config file support.

2023-08-11 11:14 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
>  	"io/ioutil"
Working on adding JSON support as well

2023-08-11 16:38 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
>  	"io/ioutil"
Added support for both JSON and YAML

2023-08-16 08:14 UTC, sagikazarmark requested changes

2023-08-16 08:14 UTC, sagikazarmark commented on cmd/bank-vaults/configure.go
> -	internalVault "github.com/bank-vaults/bank-vaults/internal/vault"
Proper import formatting:

- stdlib
- third-party
- module

2023-08-16 08:14 UTC, sagikazarmark commented on internal/vault/operator_client.go
> +	"github.com/mitchellh/mapstructure"
Same as above

2023-08-16 08:14 UTC, sagikazarmark commented on cmd/bank-vaults/configure.go
> -	internalVault "github.com/bank-vaults/bank-vaults/internal/vault"
golangci-lint run --fix should fix it, no? How is your IDE setup?

2023-08-16 08:19 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
> -	internalVault "github.com/bank-vaults/bank-vaults/internal/vault"
Ran lint, didn't complain. Using Goland.

2023-08-16 08:23 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
>  	"io/ioutil"
Marked resolved from meeting notes

2023-08-16 08:23 UTC, ramizpolic commented on cmd/bank-vaults/configure.go
> -	internalVault "github.com/bank-vaults/bank-vaults/internal/vault"
I manually updated it, linting still didn't help.

2023-08-16 08:23 UTC, ramizpolic commented on internal/vault/operator_client.go
> +	"github.com/mitchellh/mapstructure"
Same as above

2023-08-16 08:24 UTC, ramizpolic commented on internal/vault/operator_client.go
> +	"github.com/mitchellh/mapstructure"
Same notes like above, linting didn't help, manual did the trick, duh.

2023-08-16 10:02 UTC, sagikazarmark approved these changes

2023-08-16 10:06 UTC, merged