chore: change vault-env references to secret-init
bank-vaults/bank-vaults pull request #2529
Opened 2024-02-29 14:35 UTC by csatib02

## Overview

- This PR changes `Vault-env` references to secret-init references.

### ⚠️ WARNING: Only merge this after the secrets webhook has been created and a release has been created.

2024-03-13 13:15 UTC, akijakya requested changes
Great work so far! 💪

2024-03-13 13:15 UTC, akijakya commented on ADOPTERS.md
I think we should leave this as is, as they probably still using the old webhook at this point 😊

2024-03-13 13:15 UTC, akijakya commented on README.md
>  - [Vault operator](https://github.com/bank-vaults/vault-operator/) to make operating Hashicorp Vault on top of Kubernetes easier
```suggestion
- [Vault Operator](https://github.com/bank-vaults/vault-operator/) to make operating Hashicorp Vault on top of Kubernetes easier
```

2024-03-13 13:15 UTC, akijakya commented on README.md
> +- [Secrets webhook](https://github.com/bank-vaults/secrets-webhook) to inject secrets directly into Kubernetes pods
```suggestion
- [Secrets Webhook](https://github.com/bank-vaults/secrets-webhook) to inject secrets directly into Kubernetes pods
```

2024-04-05 10:48 UTC, ramizpolic submitted a review, later dismissed

2024-05-10 14:44 UTC, ramizpolic commented on Makefile
> -WEBHOOK_DOCKER_IMAGE = ${DOCKER_REGISTRY}/vault-secrets-webhook
this var is migration split leftover, can be removed

2024-05-13 08:24 UTC, ramizpolic approved these changes

2024-05-15 12:02 UTC, akijakya approved these changes

2024-05-15 12:03 UTC, merged